apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.postgresql
  version: v2
  metadata:
  # Connection string
  - name: connectionString
    value: "host=postgres-db user=postgres password=pushpop_secret_123 port=5432 connect_timeout=10 database=actor_state"
  - name: actorStateStore
    value: "true"
  - name: tablePrefix
    value: pushpop_
